bitget:
  symbol: BTCUSDT
  product_type: umcbl
  leverage: 10

strategy:
  portion: 0.1
  threshold: 0.3

risk:
  # maximum daily drawdown allowed before trading halts
  max_drawdown: 0.05
  # risk allocated per trade
  risk_per_trade: 0.01
  # ATR multiplier for stop loss calculation
  atr_factor: 1.5
  # minimum risk to reward ratio
  reward_ratio: 2.0
  # enable trailing stop feature
  trailing_stop: false

learning:
  optuna_trials: 50
  model_path: model.h5
