version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: trader
      POSTGRES_USER: trader
      POSTGRES_DB: trader
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
  agent:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    command: python -m ai_trader.main
    env_file:
      - .env
    depends_on:
      - db
      - prometheus
